In [3]:
import torch

In [62]:
y = torch.randn(2,3)
print('y: ', y)
print('y.shape: ', y.shape)
ysoftmax = torch.nn.functional.softmax(y.cpu().data, dim=1)
print('ysoftmax: ', ysoftmax)
print('ysoftmax.shape: ', ysoftmax.shape) 
sampled_y = torch.multinomial(torch.nn.functional.softmax(y.cpu().data, dim=1),1).squeeze().cuda()
print('sampled_y: ', sampled_y)
print('sampled_y.shape: ', sampled_y.shape)

y:  tensor([[-0.3288,  1.1829,  0.5164],
        [ 0.4383, -0.7461, -0.8067]])
y.shape:  torch.Size([2, 3])
ysoftmax:  tensor([[0.1272, 0.5767, 0.2961],
        [0.6274, 0.1920, 0.1807]])
ysoftmax.shape:  torch.Size([2, 3])
sampled_y:  tensor([1, 0], device='cuda:0')
sampled_y.shape:  torch.Size([2])


In [10]:
import torch
import torch.nn as nn

# 定义一个简单的网络
class SimpleNet(nn.Module):
    def __init__(self):
        super(SimpleNet, self).__init__()
        self.conv1 = nn.Conv2d(1, 2, 1)
        self.relu = nn.ReLU()

    def forward(self, x):
        x = self.conv1(x)
        print(x)
        x = self.relu(x)
        return x

# 初始化网络
net = SimpleNet()

# 创建一个列表来保存中间变量
activations = []

# 定义forward hook函数
def forward_hook(module, input, output):
    activations.append(output)

# 注册hook
hook = net.conv1.register_forward_hook(forward_hook)

# 假设有一个输入
input = torch.randn(1, 1, 2, 2)

# 前向传播
output = net(input)

# 此时activations列表中保存了conv1层的输出
print(activations)

tensor([[[[ 1.0494,  0.7470],
          [ 1.3082,  0.5528]],

         [[ 0.8692,  0.0067],
          [ 1.6071, -0.5470]]]], grad_fn=<ConvolutionBackward0>)
[tensor([[[[ 1.0494,  0.7470],
          [ 1.3082,  0.5528]],

         [[ 0.8692,  0.0067],
          [ 1.6071, -0.5470]]]], grad_fn=<ConvolutionBackward0>)]


In [19]:
import torch
kernel_size = [2,2]
stride = [1,1]
x = torch.randn(2,1,4,4)
print(x)
x = x.unfold(2, kernel_size[0], stride[0])
x = x.unfold(3, kernel_size[1], stride[1])
print(x)
print(x.shape)
x = x.transpose_(1, 2).transpose_(2, 3).contiguous()
# print(x)
# print(x.shape)

x = x.view(
        x.size(0), x.size(1), x.size(2),
        x.size(3) * x.size(4) * x.size(5))
# print(x)
# print(x.shape)
a=x
spatial_size = a.size(1) * a.size(2)
# print(spatial_size)
a = a.view(-1, a.size(-1))
# print(a)
# print(a.shape)

tensor([[[[-0.0886, -0.2883, -0.9615, -0.1326],
          [ 1.0096, -0.1389,  0.0117,  0.6096],
          [-1.2390,  0.5908,  0.4903, -0.6616],
          [-0.0071,  1.2974, -1.8786,  0.5347]]],


        [[[ 0.9867, -0.8508,  0.2260,  0.0640],
          [ 0.4050,  1.8907,  0.5577, -0.1706],
          [-0.5433, -0.3055,  0.1924,  0.1597],
          [-0.5467,  0.1248, -1.3927,  2.1104]]]])
tensor([[[[[[-0.0886, -0.2883],
            [ 1.0096, -0.1389]],

           [[-0.2883, -0.9615],
            [-0.1389,  0.0117]],

           [[-0.9615, -0.1326],
            [ 0.0117,  0.6096]]],


          [[[ 1.0096, -0.1389],
            [-1.2390,  0.5908]],

           [[-0.1389,  0.0117],
            [ 0.5908,  0.4903]],

           [[ 0.0117,  0.6096],
            [ 0.4903, -0.6616]]],


          [[[-1.2390,  0.5908],
            [-0.0071,  1.2974]],

           [[ 0.5908,  0.4903],
            [ 1.2974, -1.8786]],

           [[ 0.4903, -0.6616],
            [-1.8786,  0.5347]]]]],




     